### ISSUE TITLE
No update yet today

### ISSUE THREAD

**Issue by chrisjbillington** [ulklc/covid19-timeseries#10]
Just in case you didn't notice, I thought I'd point out the data hasn't updated yet today. Perhaps the automated scraper has failed?

**Comment by chrisjbillington** [comment]
I'm sorry, I didn't mean to add the "data correction" label, but there doesn't seem to be any way to remove it.

**Comment by ulklc** [comment]
Hi Chris,

Sorry, seems schedule task stucked because of report generation takes more than 1 minute, i moved it to same cronjob, probably it will not happen again :}

**Comment by chrisjbillington** [comment]
Thank you! Feel free to close, unless you want to consider this a bug in the automation and close it when that's fixed

**Comment by ulklc** [comment]
seems fixed,
