### ISSUE TITLE
MS Zaandam

### ISSUE THREAD

**Issue by iandoug** [ulklc/covid19-timeseries#11]
Hi

How will cases from ship MS Zaandam be handled?

Thanks, Ian

**Comment by ulklc** [comment]
Hi Ian,

MS Zaandam and Anguilla added to crawler mapping today, these will be available in 29.03.2020 reports.

Thanks

**Comment by iandoug** [comment]
Shouldn't the region be Americas rather than Asia for Zaandam?

**Comment by ulklc** [comment]
Oh my bad, can you provide me current location of ship for correction ?

**Comment by iandoug** [comment]
Appears to be at destination in San Diego.

https://www.cruisemapper.com/ships/ms-Maasdam-670

**Comment by ulklc** [comment]
Updated.

**Comment by iandoug** [comment]
Sorry, that site is wrong. Appears to be heading for Florida. 
https://www.theguardian.com/world/2020/mar/31/cruise-ship-chief-zaandam-and-rotterdam-passengers-left-to-fend-for-themselves-covid-19-crisis
