### ISSUE TITLE
Confirmed Cases dropped for France

### ISSUE THREAD

**Issue by gihco** [ulklc/covid19-timeseries#16]
The confirmed cases for France dropped on 165,027 to 147,969 on 2020-04-17.

I understand that there is a debate on which numbers are the correct ones - and probably there isn't a definite right or wrong here (see [1]). 

However, as confirmed cases cannot drop by nature I would propose to decide for one way of counting and staying to that (incl. "correcting" history accordingly). As far as I can tell the primary source for France is [2].

[1] https://github.com/CSSEGISandData/COVID-19/issues/2270
[2] https://www.gouvernement.fr/info-coronavirus/carte-et-donnees

PS: This dataset is one of the best I could find so far! Many thanks for that!!

**Comment by ulklc** [comment]
Hi @gihco 
Thanks for your correction, i am checking everyday for inconsistency. But last 3 days i did not have a time, sorry.
Here is data corrections today:
FR 2020/04/16 => Confirmed 165027 to 147969
CM 2020/04/15 => Recovered 165 to 164
CN recovered cases is dropped to 77029, after verify, i'll update between 2020/04/06 and 2020/04/18
GB recovered cases is dropped to 0, i am still investigating valid source.
LU 2020/04/13 => Death 69 to 67
UG 2020/04/17 => Recovered 56 to 55
UY 2020/04/14 => Confirmed 512 to 483
UY 2020/04/13 => Confirmed 493 to 483

This changes will be available today.

Thanks

**Comment by ulklc** [comment]
Changes applied
