### ISSUE TITLE
250 positive cases in Chile are missing.

### ISSUE THREAD

**Issue by ivanMSC** [ulklc/covid19-timeseries#18]
**Country Code / Name**
CL / Chile

**Correction**
Confirmed: {2020/03/29} - {15135}
Death: {2020/03/29} - {216}
Cured: {2020/03/29} - {8057}

**Source**
https://www.gob.cl/coronavirus/cifrasoficiales/

![image](https://user-images.githubusercontent.com/35350256/80674668-8b8de280-8a80-11ea-9dcd-57efb1f794b3.png)

paging @ulklc

**Comment by ulklc** [comment]
Hi @ivanMSC 
probably you are mentioning 2020/04/29
Its fixed, and will available today.

Thanks

**Comment by ivanMSC** [comment]
Uh... yes! April haha

Thank you!
