### ISSUE TITLE
Update of 16 May

### ISSUE THREAD

**Issue by iandoug** [ulklc/covid19-timeseries#19]
Hi

Seems like there is a problem with today's raw file ... most countries not updated?

Thanks, Ian

**Comment by ulklc** [comment]
Hi @iandoug ,
Seems crawler crashed because of destination site changes, i fixed it. Today i'll sync 14 and 15 may with CSSEGISandData/COVID-19, thanks for inform

**Comment by ulklc** [comment]
may 15 updated, thansk

**Comment by iandoug** [comment]
Sorted, thanks :-)

Cheers, Ian
