### ISSUE TITLE
Chile death and cured are switched

### ISSUE THREAD

**Issue by ivanMSC** [ulklc/covid19-timeseries#2]
I was seeing the raw report and, as a Chilean, I was looking at your data for my country. You have death count and cured count switched! Not sure if this issue repeats for some other country.

Edit:
Oh yeah, it's a bug

![image](https://user-images.githubusercontent.com/35350256/77380206-5099e000-6d59-11ea-8712-5452e0c4e83e.png)

**Comment by ulklc** [comment]
I was adding region column, you may have pulled data while my commit ^^, And can you clear my mind how is it switched ? graph is looking good and correct i guess

**Comment by ivanMSC** [comment]
It's the column headers that are switched. 

it now is
`day,countryCode,countryName,region,lat,lon,confirmed,cured,death`

it should be
`day,countryCode,countryName,region,lat,lon,confirmed,death,cured`

**Comment by ivanMSC** [comment]
![image](https://user-images.githubusercontent.com/35350256/77380950-57c1ed80-6d5b-11ea-9d17-bd31a84bae3a.png)

**Comment by ulklc** [comment]
Its weird, let me check

**Comment by ulklc** [comment]
Okay i found! This issue same for other files, I am fixing it now and re-generate reports.

**Comment by ulklc** [comment]
Lets check again @ivanMSC ref: https://github.com/ulklc/covid19-timeseries/commit/d926b8b68f50e30151d29d8784e948b916eb72a3

**Comment by ivanMSC** [comment]
![image](https://user-images.githubusercontent.com/35350256/77381714-5a254700-6d5d-11ea-984c-804e82dfc3b4.png)

There we go!
