### ISSUE TITLE
No Update since 2020-06-18

### ISSUE THREAD

**Issue by LaChirla** [ulklc/covid19-timeseries#23]
will the **covid19-timeseries** be continued?

**Comment by iandoug** [comment]
Can you please advise re situation so that we can make alternative arrangements if necessary. 

Thanks.

**Comment by ulklc** [comment]
Hi,
Unfortunately, my droplet that includes crawlers shut down. I wasn't aware of that. I'll sync missing times with https://github.com/CSSEGISandData/COVID-19 in one or two days. 
Thanks

**Comment by ulklc** [comment]
Edit:
Outbound traffic was blocked, i fixed it right now. So we dont need to worry about missing days, it was already commited, but not pushed to git.
Thanks

**Comment by ivanMSC** [comment]
Great! I was about to do some serious refactoring! haha

**Comment by iandoug** [comment]
Thanks a mill :-)

**Comment by ulklc** [comment]
Currently, I don't have any plans to archive this repo. If I do such a thing in the future, I will notify the people who are dependent on this repo before 1 month :}

Also, i'll share codebase of crawlers in one or two weeks. Sorry guys, nowadays i am really busy with works. Sometimes i am forgetting to checking alarms.

**Comment by LaChirla** [comment]
I'm very happy, that it is working again. Thank you a lot.

**Comment by iandoug** [comment]
Hi

> Also, i'll share codebase of crawlers in one or two weeks. 

Are you still planning to do this?

Thanks, Ian
