### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by iandoug** [ulklc/covid19-timeseries#5]
Thanks... JH is a mess.

For mapping purposes, it would be better if the Channel Isles were split into their "country codes" ... don't know if that is doable.

Thanks, Ian

**Comment by ulklc** [comment]
Hi Ian,
Many sources is assuming Jersey and Guernsey as channel island. I would like to, but currently it is little bit hard :/

**Comment by iandoug** [comment]
Not a train smash, I shove them under GB.
