### ISSUE TITLE
#Warning# "cured" will be changed with "recovered"

### ISSUE THREAD

**Issue by pdobsan** [ulklc/covid19-timeseries#8]
Thank you for providing these data sets! In the view of JSU's dropping the `recovered`, yours is particularly welcome. May I ask how you collect them, is the crawling code publicly available?

Is the `cured` different from the JSU's former category `recovered`? If not, `cured` is a bit missleading name, `recovered` would be more appropriate, I believe.

**Comment by ulklc** [comment]
Yep, i agree. I am labelling this issue as enhancement, and it will be replaced as "recovered" next report generation.

**Comment by ulklc** [comment]
And currently crawling code is not opensource yet (I didnt pushed codebase to github yet :]). I have a plan to share it after the re-structure.

**Comment by shubhrampandey** [comment]
Thanks for sharing the data. It will be very helpful for many app developers as JHU dropped the recovered cases it is very much appreciated that you kept it as cured cases. 
Just want to ask one: what is the frequency of updating the data and how much it is reliable.
Please don't take my questing another way.
Once again thanks for this repository, I know many people who are dependent on JHU data so now the traffic on this repository going to increase.

**Comment by ulklc** [comment]
Actually my snapshots is not reliable much. Crawlers are taking snapshot every hours and compare with history. If snapped data is lower than history crawlers is sending notification to me. I am checking notifications and updating mongo database with other sources as manually. For community corrections, i already created issue template. With this way i hope we can increase data reliablity. Recovered values is not providing from WHO anymore. But some dashboards is still providing this data from user reports. Final snapshots is uploading every day at 00:00 GMT-0.

**Comment by shubhrampandey** [comment]
> Actually my snapshots is not reliable much. Crawlers are taking snapshot every hours and compare with history. If snapped data is lower than history crawlers is sending notification to me. I am checking notifications and updating mongo database with other sources as manually. For community corrections, i already created issue template. With this way i hope we can increase data reliablity. Recovered values is not providing from WHO anymore. But some dashboards is still providing this data from user reports. Final snapshots is uploading every day at 00:00 GMT-0.

Ok!!!! Thanks....So will you still provide the recovered data?

**Comment by ulklc** [comment]
As long as any web site shares the number of recovered people, I will continue to provide

**Comment by pdobsan** [comment]
> Yep, i agree. I am labelling this issue as enhancement, and it will be replaced as "recovered" next report generation.

Great, thank you. Just an other minor nitpick. I suggest to use exactly the same category names what JSU used, that is `confirmed`, `recovered` and `deaths` ; note the last. That would increase
the likelihood of people transitioning to your API.

**Comment by shubhrampandey** [comment]
Ok...Thanks a lot....Hence I am referrening to yoru repo...

You can check the current status of the app here: https://shubhrampandey.shinyapps.io/coronaVirusViz/

**Comment by shubhrampandey** [comment]
Also could you please let me know the country code follow which standard naming convention like ISO2 or ISO3 as I have to use it in spatial map
Thanks

**Comment by ulklc** [comment]
ISO 3166-1 alpha-2

**Comment by ulklc** [comment]
Changes deployed
