### ISSUE TITLE
Recovered data

### ISSUE THREAD

**Issue by daniel-karl** [ulklc/covid19-timeseries#9]
Hi @ulklc 

could you explain more how exactly you obtain "recovered" data?

I would like to use it as part of https://covid19map.io (check how beautiful it used to be when selecting the Johns Hopkins v1 data set, before they decided to drop the recovered data).

Thanks a lot for your work,
Daniel

**Comment by ulklc** [comment]
Hi Daniel,

I explained in #8 
https://github.com/ulklc/covid19-timeseries/issues/8#issuecomment-603302142

And sources are listed on readme.

Thanks
